apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubernetes-deployment
spec:
  selector:
    matchLabels:
      app: springboot-kubernetes
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: springboot-kubernetes
    spec:
      containers:
      - name: springboot-kubernetes-demo
        image: vaibhavdave10990/springboot-kubernetes:4.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: springboot-kubernetes-service
spec:
  selector:
    app: springboot-kubernetes
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP